### PR TITLE
Empty multiset is empty

### LINKED ISSUE #53: Multiset's isEmpty returns false even if count == 0
Declared (and desired) behavior for isEmpty – True iff `count` is 0 – differs from actual behavior:

schermata 2015-06-02 alle 18 33 59

### PR DESCRIPTION
**Pull request by robrix**
Fixes #53.

### CODE REVIEW

**Comment by madbat** [comment]
Awesome, thank you :+1:

**Comment by robrix** [comment]
CI passed; simple change; demonstrated failure & fix with tests. I have fairly high confidence as a result so gonna self-merge & cut a new release.

**Comment by robrix** [comment]
Just tagged https://github.com/robrix/Set/releases/tag/1.4.1

**Comment by madbat** [comment]
Fantastic, thank you @robrix!

I can confirm that Multiset 1.4.1 works perfectly for me now in [SwiftMath](https://github.com/madbat/SwiftMath) 🎊

**Comment by robrix** [comment]
:bow: Glad I could help!

**Pull request merged**
